import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// SINGLE SOURCE — everything from design-tokens.context.ts
import { 
  COLORS_LIGHT, 
  FONT_FAMILY,
  TYPOGRAPHY,
  M3_SHAPE_SCALE, 
  M3_EASING, 
  M3_DURATION,
  COLORS_MARKETING,
  MARKETING_SHADOW,
  GRADIENT_TEXT,
  MARKETING_TYPOGRAPHY,
} from '../../context/domains/design-tokens.context';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = path.join(__dirname, '../src/styles/variables.css');

// Flattener — convert nested objects to CSS variables
function toCssVars(obj: Record<string, unknown>, prefix: string): string[] {
  const vars: string[] = [];
  for (const [key, value] of Object.entries(obj)) {
    const varName = `${prefix}-${key.replace(/[A-Z]/g, m => `-${m.toLowerCase()}`).replace(/_/g, '-')}`;
    if (typeof value === 'object' && value !== null) {
      vars.push(...toCssVars(value as Record<string, unknown>, varName));
    } else {
      vars.push(`  --${varName}: ${value};`);
    }
  }
  return vars;
}

// Generate
const lines = [
  '/* ----------------------------------------------------------------------- */',
  '/* [GENERATED] DO NOT EDIT — source: context/domains/design-tokens.context.ts */',
  '/* Generated by: website/scripts/generate-css.ts                           */',
  '/* ----------------------------------------------------------------------- */',
  '',
  ':root {',
];

// Base colors
lines.push('  /* COLORS */');
lines.push(...toCssVars(COLORS_LIGHT, 'color'));

// Marketing colors
lines.push('');
lines.push('  /* MARKETING COLORS */');
lines.push(...toCssVars(COLORS_MARKETING, 'color-mkt'));

// Typography
lines.push('');
lines.push('  /* TYPOGRAPHY */');
lines.push(`  --font-family: ${FONT_FAMILY};`);
lines.push(`  --font-family-marketing: ${MARKETING_TYPOGRAPHY.fontFamily};`);
lines.push(...toCssVars(TYPOGRAPHY, 'type'));

// M3 Shape Scale
lines.push('');
lines.push('  /* M3 SHAPE SCALE */');
lines.push(...toCssVars(M3_SHAPE_SCALE, 'radius'));

// Marketing shadow
lines.push('');
lines.push('  /* MARKETING SHADOW */');
lines.push(`  --shadow-blue-glow: ${MARKETING_SHADOW.blueGlow};`);

// Gradient text
lines.push('');
lines.push('  /* GRADIENT TEXT */');
for (const [name, gradient] of Object.entries(GRADIENT_TEXT)) {
  lines.push(`  --gradient-${name}-from: ${gradient.from};`);
  lines.push(`  --gradient-${name}-to: ${gradient.to};`);
}

// Motion
lines.push('');
lines.push('  /* M3 EASING */');
lines.push(...toCssVars(M3_EASING, 'ease'));

lines.push('');
lines.push('  /* M3 DURATION */');
lines.push(...toCssVars(M3_DURATION, 'duration'));

lines.push('}');

// Write
fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
fs.writeFileSync(OUTPUT_PATH, lines.join('\n'));

const varCount = lines.filter(l => l.trim().startsWith('--')).length;
console.log(`✅ CSS Variables generated: ${OUTPUT_PATH} (${varCount} variables)`);
